### ISSUE TITLE
Doesn't allow receiving CTRL-C (SIGINT) signal

### ISSUE THREAD

**Issue by alvatar** [sethgrid/multibar#5]
Hi,

Under OSX, different terminals (terminal, iterm2), and shells (bash, zsh) don't seem to process the signals when the bars are displayed (it doesn't respond). You need to send it directly with the _kill_ program to the process. And, when you do so, the shell is broken and you need to manually reset it.

This is the code I'm using:

```go
	sigc := make(chan os.Signal, 1)
	signal.Notify(sigc,
		os.Interrupt,
		syscall.SIGHUP,
		syscall.SIGINT,
		syscall.SIGTERM,
		syscall.SIGQUIT)
	go func() {
		s := <-sigc
		log.Fatal("Exit with incomplete download")
		os.Exit(1)
	}()
```

Awesome library, thank you! :+1:

**Comment by sethgrid** [comment]
Sorry for the _very_ late response. I had notifications turned off and did not see this. 

I tested out signal handling and it appears to be working (maybe I pushed up a change after this issue was made?). You can check out the tests added with this [commit](https://github.com/sethgrid/multibar/commit/4bf4cf7b87d60bfaf4b4ec40fc7aabf376d0be37).

If you run [this test](https://github.com/sethgrid/multibar/tree/master/manual_tests/signal_handling) with a `go run main.go`, it will show signal handling working. Similarly, you can run the [demo](https://github.com/sethgrid/multibar/tree/master/demo) and send a `ctl+c` to it. 

Cheers!
